before_script:
  - buildDir=$(pwd); echo $buildDir
  - projectDir=~/front/{{ .ProName }}; echo $projectDir
  - mkdir -p $(dirname $projectDir); ln -sfT $buildDir $projectDir; cd $projectDir

stages:
  - deploy

variables:
  GIT_CLEAN_FLAGS: none

.deploy:
  stage: deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_NAME-{{ .Domain }}
  script:
    - yum install
    - yum run build
    - xiaomei web deploy $CI_ENVIRONMENT_NAME -Wb "docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY"
  tags:
    - shell-xiaomei-qa  # match shell runner for qa that has xiaomei command.
  variables:
    branch: ""
  rules:
    - if: [ '$CI_COMMIT_REF_NAME == $branch' ]

deploy-qa:
  extends: .deploy
  variables:
    branch: qa

deploy-qa2:
  extends: .deploy
  variables:
    branch: qa2

deploy-preview:
  extends: .deploy
  tags:
    - shell-xiaomei-production # match shell runner for production that has xiaomei command.
  variables:
    branch: preview

deploy-production:
  extends: deploy-preview
  environment:
    name: production
    url: https://{{ .Domain }}
  variables:
    branch: master
  rules:
    - if: [ '$CI_COMMIT_REF_NAME == $branch' ]
      when: manual
  allow_failure: false

