name: {{ .ProName }}
timeZone: { name: China, offset: 28800 }
# mailer://smtp.exmail.qq.com:465/?user=报警<alarm@{{ .Domain }}>&pass=123456
mailer: "mailer://smtp.qq.com:25/?user=小美<xiaomei-go@qq.com>&pass=zjsbosjlhgugechh"
keepers: [ "小美<xiaomei-go@qq.com>" ]
externalURL: https://preview-{{ .Domain }}
cookie:
  name: token
  domain: preview-{{ .Domain }}
  path: /
  maxAge: 1M # Y:年; M:月; D:天; h:时; m:分; s:秒
secret: {{ genSecret }}
