name: {{ .ProName }}
timeZone: { name: China, offset: 28800 }
# mailer://smtp.exmail.qq.com:465/?user=报警<alarm@{{ .Domain }}>&pass=123456
mailer: "mailer://smtp.qq.com:25/?user=小美<xiaomei-go@qq.com>&pass=zjsbosjlhgugechh"
keepers: [ ]
externalURL: http://localhost:3000/api
secret: {{ genSecret }}
data:
  postgres:
    default: postgres://postgres:@localhost/{{.ProName}}_test
  mysql:
    default: root:root@tcp(127.0.0.1:3306)/{{.ProName}}_test
  mongo:
    default: mongodb://10.249.6.30/{{.ProName}}_test
  redis:
    default: redis://:@localhost:6379/0
